"""Tests for ingest/canonicalizer.py. Purely deterministic, no LLM."""

from __future__ import annotations

import pytest

from app.ingest.canonicalizer import (
    UNRESOLVED_METRIC_ID,
    CanonicalMetric,
    _build_label_index,
    _normalize_label,
    all_metric_ids,
    canonicalize_facts,
    canonicalize_label,
    expense_metric_ids,
    normalize_label,
    resolve_canonical_metric,
)
from app.ingest.fact_extractor import ExtractedFact


# =============================================================================
# Label normalization
# =============================================================================

@pytest.mark.parametrize("raw,normalized", [
    ("Total revenues", "total revenues"),
    ("  Total revenues  ", "total revenues"),
    ("Total revenues:", "total revenues"),
    ("Services (1)", "services"),
    ("Stockholders’ equity", "stockholders' equity"),
])
def test_normalize_label(raw, normalized):
    assert _normalize_label(raw) == normalized


# =============================================================================
# Resolution against the real registry (golden pairs, hand-verified against
# the actual Tesla and Apple filings this session)
# =============================================================================

@pytest.mark.parametrize("label,expected_metric_id", [
    ("Total revenues", "METRIC_TOTAL_REVENUE"),
    ("Total net sales", "METRIC_TOTAL_REVENUE"),
    ("total revenue", "METRIC_TOTAL_REVENUE"),  # natural-language synonym
    ("Gross profit", "METRIC_GROSS_PROFIT"),
    ("Gross margin", "METRIC_GROSS_PROFIT"),
    ("Net income", "METRIC_NET_INCOME"),
    ("Net income attributable to common stockholders", "METRIC_NET_INCOME_ATTRIBUTABLE_COMMON"),
    ("Total stockholders’ equity", "METRIC_TOTAL_EQUITY"),
    ("Net cash provided by operating activities", "METRIC_OPERATING_CASH_FLOW"),
    ("Cash generated by operating activities", "METRIC_OPERATING_CASH_FLOW"),
])
def test_resolve_canonical_metric_known_labels(label, expected_metric_id):
    assert resolve_canonical_metric(label) == expected_metric_id


def test_resolve_canonical_metric_unrecognized_label_returns_none():
    assert resolve_canonical_metric("Services (1)") is None


def test_canonicalize_label_flags_unrecognized_rather_than_guessing():
    result = canonicalize_label("Digital assets")
    assert result.metric_canonical_id is None
    assert len(result.ambiguity_flags) == 1
    assert "unrecognized_label" in result.ambiguity_flags[0]


def test_net_income_and_attributable_variant_never_collide():
    """The near-miss guard the write-up calls out explicitly: these must
    resolve to different canonical IDs, never the same one."""
    a = resolve_canonical_metric("Net income")
    b = resolve_canonical_metric("Net income attributable to common stockholders")
    assert a != b
    assert a == "METRIC_NET_INCOME"
    assert b == "METRIC_NET_INCOME_ATTRIBUTABLE_COMMON"


def test_bare_profit_never_collides_with_gross_or_operating_profit():
    """Bare "profit" colloquially means the bottom line (net income) in
    everyday financial usage, but real filings always qualify gross and
    operating profit explicitly -- these three must stay distinct."""
    assert resolve_canonical_metric("profit") == "METRIC_NET_INCOME"
    assert resolve_canonical_metric("Gross profit") == "METRIC_GROSS_PROFIT"
    assert resolve_canonical_metric("operating profit") == "METRIC_OPERATING_INCOME"


def test_registry_collision_raises_at_build_time():
    """Two different metrics claiming the same normalized label is a
    registry authoring bug and must fail loudly, not silently pick one."""
    conflicting = [
        CanonicalMetric(metric_id="A", display_name="A", statement="income_stmt", known_labels=["Revenue"]),
        CanonicalMetric(metric_id="B", display_name="B", statement="income_stmt", known_labels=["revenue"]),
    ]
    with pytest.raises(ValueError, match="collision"):
        _build_label_index(conflicting)


# =============================================================================
# canonicalize_facts: batch resolution for ingestion
# =============================================================================

def _extracted_fact(label: str, value: float = 100.0, units: str = "USD_millions") -> ExtractedFact:
    return ExtractedFact(
        metric_raw_label=label, year=2025, value=value, units=units,
        filing_id="TSLA-10K-2025-12-31", page_number=61,
        table_id="TSLA-10K-2025-12-31::page61::table1", row_id=1,
    )


def test_canonicalize_facts_resolves_known_labels():
    records = canonicalize_facts([_extracted_fact("Total revenues")], company_ticker="TSLA")
    assert records[0].metric_canonical_id == "METRIC_TOTAL_REVENUE"
    assert records[0].company_ticker == "TSLA"
    assert records[0].ambiguity_flags == []


def test_canonicalize_facts_keeps_unresolved_facts_stored_not_dropped():
    """Guard 2 of the write-up: ambiguous facts are still stored and
    retrievable, flagged, not silently discarded."""
    records = canonicalize_facts([_extracted_fact("Digital assets")], company_ticker="TSLA")
    assert len(records) == 1
    assert records[0].metric_canonical_id == UNRESOLVED_METRIC_ID
    assert len(records[0].ambiguity_flags) == 1


# =============================================================================
# Units-disambiguated labels: "Basic"/"Diluted" mean genuinely different
# things (a per-share dollar figure vs. a share count) depending on units.
# Confirmed against real Tesla 10-K data: both meanings use the identical
# bare label text in different sections of the same table.
# =============================================================================

@pytest.mark.parametrize("label,units,expected_metric_id", [
    ("Basic", "per_share", "METRIC_EPS_BASIC"),
    ("Diluted", "per_share", "METRIC_EPS_DILUTED"),
    ("Basic", "shares_millions", "METRIC_WEIGHTED_AVG_SHARES_BASIC"),
    ("Diluted", "shares_millions", "METRIC_WEIGHTED_AVG_SHARES_DILUTED"),
])
def test_basic_diluted_resolve_by_units(label, units, expected_metric_id):
    assert resolve_canonical_metric(label, units=units) == expected_metric_id


def test_basic_diluted_without_units_is_unresolved_not_guessed():
    result = canonicalize_label("Basic", units=None)
    assert result.metric_canonical_id is None
    assert "ambiguous_without_units" in result.ambiguity_flags[0]


def test_basic_diluted_with_unrecognized_units_is_unresolved_not_guessed():
    result = canonicalize_label("Basic", units="percent")
    assert result.metric_canonical_id is None


def test_canonicalize_facts_disambiguates_basic_by_units():
    """The batch ingestion path has units on ExtractedFact and must use
    them; this is the actual code path fact_extractor.py -> canonicalizer.py
    exercises, not just the unit-level resolve_canonical_metric() helper."""
    facts = [
        _extracted_fact("Basic", value=1.18, units="per_share"),
        _extracted_fact("Basic", value=3225.0, units="shares_millions"),
    ]
    records = canonicalize_facts(facts, company_ticker="TSLA")
    ids = {r.metric_canonical_id for r in records}
    assert ids == {"METRIC_EPS_BASIC", "METRIC_WEIGHTED_AVG_SHARES_BASIC"}


@pytest.mark.parametrize("label,expected_metric_id", [
    ("diluted eps", "METRIC_EPS_DILUTED"),
    ("basic earnings per share", "METRIC_EPS_BASIC"),
    ("SG&A", "METRIC_SGA"),
    ("Selling, general and administrative", "METRIC_SGA"),
    ("profit", "METRIC_NET_INCOME"),
])
def test_full_phrase_labels_resolve_without_units(label, expected_metric_id):
    """A user's natural-language question ('Tesla's diluted EPS') supplies
    enough context in the phrase itself; the online query path never has
    units available and must not need them for these."""
    assert resolve_canonical_metric(label) == expected_metric_id


# =============================================================================
# Segment revenue metrics (Tesla's Automotive / Energy breakdown). Added
# after a real live-tested gap: "revenue from car sales" did not match
# the exact filing text "Automotive sales" -- the fix is curated synonyms
# here, not fuzzy matching on the numeric path.
#
# "Automotive sales", "Automotive leasing", and "Services and other" are
# deliberately NOT canonical metrics and must stay unresolved: Tesla's
# own income statement reuses each exact text for two different line
# items (once under "Revenues", once under "Cost of revenues", confirmed
# against the actual filing PDF) with genuinely different values for the
# same period. See the long comment above their names' absence in
# CANONICAL_METRICS for the full story -- this is the same "same label,
# two meanings" problem the write-up's near-miss guard exists for, just
# discovered one level deeper than the registry alone can currently
# resolve.
# =============================================================================

@pytest.mark.parametrize("label,expected_metric_id", [
    ("Automotive regulatory credits", "METRIC_AUTOMOTIVE_REGULATORY_CREDITS"),
    ("regulatory credits", "METRIC_AUTOMOTIVE_REGULATORY_CREDITS"),
    ("Total automotive revenues", "METRIC_TOTAL_AUTOMOTIVE_REVENUE"),
    ("automotive revenue", "METRIC_TOTAL_AUTOMOTIVE_REVENUE"),
    ("Energy generation and storage sales", "METRIC_ENERGY_SALES"),
    ("energy storage sales", "METRIC_ENERGY_SALES"),
    ("Energy generation and storage leasing", "METRIC_ENERGY_LEASING"),
    ("Energy generation and storage segment revenue", "METRIC_TOTAL_ENERGY_REVENUE"),
    ("total energy revenue", "METRIC_TOTAL_ENERGY_REVENUE"),
])
def test_segment_revenue_labels_resolve(label, expected_metric_id):
    assert resolve_canonical_metric(label) == expected_metric_id


@pytest.mark.parametrize("label", [
    "Automotive sales", "car sales", "revenue from car sales", "vehicle sales revenue",
    "Automotive leasing", "car leasing revenue",
    "Services and other", "services revenue",
])
def test_ambiguous_revenue_vs_cost_labels_stay_unresolved(label):
    """These exact raw label texts are reused by Tesla for a different
    line item under "Cost of revenues" with a different real value for
    the same period -- resolving them to a single canonical id would
    silently merge two different figures. Must stay unresolved (and thus
    reachable only via the raw-label fallback, which will itself
    correctly surface the resulting conflict rather than guess) until
    the extraction pipeline captures which section of the table a row
    came from."""
    assert resolve_canonical_metric(label) is None


# =============================================================================
# is_expense flag / registry scan helpers, for the ranking question_type
# =============================================================================

def test_expense_metric_ids_is_curated_not_inferred():
    """SG&A, cost of revenue, and total operating expenses are hand-curated
    expense line items; a profit or revenue metric must never appear here
    even though its name might superficially suggest it."""
    ids = set(expense_metric_ids())
    assert ids == {"METRIC_COST_OF_REVENUE", "METRIC_OPERATING_EXPENSES", "METRIC_SGA"}


def test_all_metric_ids_covers_every_registry_entry():
    assert set(all_metric_ids()) >= {
        "METRIC_TOTAL_REVENUE", "METRIC_NET_INCOME", "METRIC_SGA", "METRIC_TOTAL_ASSETS",
    }
    assert len(all_metric_ids()) == len(set(all_metric_ids()))  # no duplicate ids


def test_expense_metric_ids_is_subset_of_all_metric_ids():
    assert set(expense_metric_ids()) <= set(all_metric_ids())


def test_normalize_label_is_public_wrapper_around_the_same_rule():
    """agents/fact_retriever.py's raw-label fallback for segment metrics
    (e.g. "AWS revenue") must use the identical normalization rule the
    registry itself uses, not a second, drifting definition."""
    assert normalize_label("  Energy Generation and Storage Segment Revenue  ") == \
        _normalize_label("  Energy Generation and Storage Segment Revenue  ")
    assert normalize_label("Foo (1)") == "foo"
